name: Ali-DevOps-Bot
on: [push] #This triggers the bot on every push

jobs:
  greet:
    runs-on: ubuntu-latest #The bot lives on a temporary Linux server
    steps:
      - name: Say Hello
        run: echo "Ali, your code was successfully pushed to the cloud!"

